# 生成ndarray

### array方法

1. array接受任意 [序列型对象],生成一个新的包含传递数据NumPy数组


In [6]:
import numpy as np

In [7]:
data_1 = [6, 3.4, 9, 5, 7]

In [8]:
arr = np.array(data_1)

In [4]:
arr

array([6. , 3.4, 9. , 5. , 7. ])

2. 嵌套序列，等长度的列表，将会转换 <b>多维数组</b>

In [13]:
data_2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [14]:
arr = np.array(data_2)

In [15]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

* ndim： 数组行数
* shape：数组形状

In [18]:
arr.ndim

2

In [19]:
arr.shape

(2, 4)

# ndarray的数据类型

* ndarray的数据类型存储在dtype属性[元数据]当中
* 除非显式的指定，否则numpy会自动推断生成数组的数据类型

In [5]:
arr.dtype

dtype('float64')

In [20]:
arr1 = np.array([1, 2, 3], dtype='float')

In [21]:
arr2 = np.array([1, 2, 3], dtype='int')

In [24]:
arr1.dtype

dtype('float64')

In [25]:
arr2.dtype

dtype('int32')

* 使用astype方法替换数组的数据类型
* astype方法是将数组复制并替换成目标数据类型，在返回修改后的数组
    * astype方法不会修改数组

In [32]:
arr = np.array([1, 2, 3, 4, 5])

In [33]:
arr.dtype

dtype('int32')

In [34]:
float_arr = arr.astype(np.float64)

In [37]:
float_arr.dtype

dtype('float64')

* 浮点数转换整数类型是将小数点后的数据忽略
* float -> int -> float 将会丢失数据

In [38]:
arr = np.array([3.1, 4.32, 5.33])

In [39]:
float_arr = arr.astype(np.int32)

In [40]:
float_arr

array([3, 4, 5])

In [41]:
int_arr = float_arr.astype(np.float64)

In [42]:
int_arr

array([3., 4., 5.])

* 可以从其他ndarray数组中获取dtype属性，做类型转换

In [44]:
int_arr = np.arange(10)

In [45]:
calibers = np.array([.22, .39, .13, .567], dtype=np.float64)

In [46]:
int_arr.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

# NumPy数组算术

In [48]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [49]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [50]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [51]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [52]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

* 数组之间的比较会产生布尔值

In [53]:
arr2 = np.array([[1., 0.22, 2.3], [7.2, 5.4, 1.4]])

In [54]:
arr2 > arr

array([[False, False, False],
       [ True,  True, False]])

# 基础索引与切片