In [1]:
import numpy as np

# ndarray的数据类型

* ndarray的数据类型存储在dtype属性[元数据]当中
* 除非显式的指定，否则numpy会自动推断生成数组的数据类型

In [2]:
data = [[1, 2, 3], [4, 5, 6]]

In [3]:
arr = np.array(data)

In [4]:
arr.dtype

dtype('int32')

In [5]:
arr1 = np.array([1, 2, 3], dtype='float')

In [6]:
arr2 = np.array([1, 2, 3], dtype='int')

In [7]:
arr1.dtype

dtype('float64')

In [8]:
arr2.dtype

dtype('int32')

* 使用astype方法替换数组的数据类型
* astype方法是将数组复制并替换成目标数据类型，在返回修改后的数组
    * astype方法不会修改数组

In [9]:
arr = np.array([1, 2, 3, 4, 5])

In [10]:
arr.dtype

dtype('int32')

In [11]:
float_arr = arr.astype(np.float64)

In [12]:
float_arr.dtype

dtype('float64')

* 浮点数转换整数类型是将小数点后的数据忽略
* float -> int -> float 将会丢失数据

In [13]:
arr = np.array([3.1, 4.32, 5.33])

In [14]:
float_arr = arr.astype(np.int32)

In [15]:
float_arr

array([3, 4, 5])

In [16]:
int_arr = float_arr.astype(np.float64)

In [17]:
int_arr

array([3., 4., 5.])

* 可以从其他ndarray数组中获取dtype属性，做类型转换

In [18]:
int_arr = np.arange(10)

In [19]:
calibers = np.array([.22, .39, .13, .567], dtype=np.float64)

In [20]:
int_arr.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])