In [1]:
import numpy as np

# NumPy数组算术

In [2]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [3]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [4]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [6]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

* 数组之间的比较会产生布尔值

In [7]:
arr2 = np.array([[1., 0.22, 2.3], [7.2, 5.4, 1.4]])

In [8]:
arr2 > arr

array([[False, False, False],
       [ True,  True, False]])