In [1]:
import numpy as np

# 基础索引与切片

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[5]

5

In [5]:
arr[5:8]

array([5, 6, 7])

In [6]:
arr[5: 8] = 12

In [7]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

* numpy切片返回的是数组的视图
* 任何对视图的修改，都会反应到原数组上

In [8]:
arr_slice = arr[5: 8]

In [9]:
arr_slice

array([12, 12, 12])

In [10]:
arr_slice[1] = 12345

In [11]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

* 使用cope方法获取视图的拷贝

In [12]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [13]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr2d[2]

array([7, 8, 9])

In [15]:
arr2d[0][2]

3

In [16]:
arr2d[0, 2]

3

In [17]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [18]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [19]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
old_values = arr3d[0].copy()

In [21]:
arr3d[0] = 42

In [22]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [23]:
arr3d[0] = old_values

In [24]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [25]:
arr3d[1, 0]

array([7, 8, 9])

In [26]:
arr3d[0, 1]

array([4, 5, 6])

* 数组的切片索引

In [27]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [28]:
arr[1: 6]

array([ 1,  2,  3,  4, 12])

In [29]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [32]:
arr2d[1, :2]

array([4, 5])

In [33]:
arr2d[:2, 2]

array([3, 6])

In [34]:
arr2d[:2, 1:] = 0

In [35]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

* 布尔索引

In [36]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [37]:
data = np.random.randn(7, 4)

In [38]:
data

array([[-0.46708339, -1.83536376,  0.35030078,  2.99976082],
       [-0.37967422,  0.15291539, -0.88067227,  0.50558774],
       [-1.0503696 ,  2.79882734, -0.02597287, -0.70664108],
       [-0.82656576, -0.16739338, -0.6692964 , -0.75876993],
       [ 1.25324539,  1.29237842,  1.91097432, -1.27041509],
       [ 1.40820893, -1.67744571, -1.01733671, -0.29118679],
       [-0.58048516, -2.96310312, -0.85797532,  1.84927498]])

In [39]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [40]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [41]:
data[names == 'Bob']

array([[-0.46708339, -1.83536376,  0.35030078,  2.99976082],
       [-0.82656576, -0.16739338, -0.6692964 , -0.75876993]])

布尔值数组的长度必须和数组轴索引的长度一致


布尔值数组的长度不正确时， 布尔值数组选择数据的方法不会报错

In [42]:
data[names == 'Bob', : 2]

array([[-0.46708339, -1.83536376],
       [-0.82656576, -0.16739338]])

In [43]:
data[~(names != 'Bob')]

array([[-0.46708339, -1.83536376,  0.35030078,  2.99976082],
       [-0.82656576, -0.16739338, -0.6692964 , -0.75876993]])

In [44]:
cond = names == 'Bob'

In [45]:
data[~cond]

array([[-0.37967422,  0.15291539, -0.88067227,  0.50558774],
       [-1.0503696 ,  2.79882734, -0.02597287, -0.70664108],
       [ 1.25324539,  1.29237842,  1.91097432, -1.27041509],
       [ 1.40820893, -1.67744571, -1.01733671, -0.29118679],
       [-0.58048516, -2.96310312, -0.85797532,  1.84927498]])

In [46]:
mask = (names == 'Bob') | (names == 'Will')

In [47]:
mask

array([ True, False,  True,  True,  True, False, False])

In [48]:
data[mask]

array([[-0.46708339, -1.83536376,  0.35030078,  2.99976082],
       [-1.0503696 ,  2.79882734, -0.02597287, -0.70664108],
       [-0.82656576, -0.16739338, -0.6692964 , -0.75876993],
       [ 1.25324539,  1.29237842,  1.91097432, -1.27041509]])

In [49]:
data

array([[-0.46708339, -1.83536376,  0.35030078,  2.99976082],
       [-0.37967422,  0.15291539, -0.88067227,  0.50558774],
       [-1.0503696 ,  2.79882734, -0.02597287, -0.70664108],
       [-0.82656576, -0.16739338, -0.6692964 , -0.75876993],
       [ 1.25324539,  1.29237842,  1.91097432, -1.27041509],
       [ 1.40820893, -1.67744571, -1.01733671, -0.29118679],
       [-0.58048516, -2.96310312, -0.85797532,  1.84927498]])

需要注意 python 中 bool运算的关键字对布尔值数组没有效果吗需要用 & | 代替

In [50]:
data[data > 0] = 0

In [51]:
data

array([[-0.46708339, -1.83536376,  0.        ,  0.        ],
       [-0.37967422,  0.        , -0.88067227,  0.        ],
       [-1.0503696 ,  0.        , -0.02597287, -0.70664108],
       [-0.82656576, -0.16739338, -0.6692964 , -0.75876993],
       [ 0.        ,  0.        ,  0.        , -1.27041509],
       [ 0.        , -1.67744571, -1.01733671, -0.29118679],
       [-0.58048516, -2.96310312, -0.85797532,  0.        ]])

In [52]:
data[names != 'Joe'] = 7

In [53]:
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [-0.37967422,  0.        , -0.88067227,  0.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.        , -1.67744571, -1.01733671, -0.29118679],
       [-0.58048516, -2.96310312, -0.85797532,  0.        ]])