In [7]:
import numpy as np

# 数组转置和换轴

转置是数组的一种特殊的重组形式

可以返回底层数据的视图而不需要赋值任何内容

数组拥有的transpose方法， 也有T属性

In [8]:
arr = np.arange(32).reshape((8, 4))

In [9]:
arr @ arr.T

array([[  14,   38,   62,   86,  110,  134,  158,  182],
       [  38,  126,  214,  302,  390,  478,  566,  654],
       [  62,  214,  366,  518,  670,  822,  974, 1126],
       [  86,  302,  518,  734,  950, 1166, 1382, 1598],
       [ 110,  390,  670,  950, 1230, 1510, 1790, 2070],
       [ 134,  478,  822, 1166, 1510, 1854, 2198, 2542],
       [ 158,  566,  974, 1382, 1790, 2198, 2606, 3014],
       [ 182,  654, 1126, 1598, 2070, 2542, 3014, 3486]])

In [10]:
arr.transpose()

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [11]:
arr.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [12]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [13]:
arr = np.random.randn(6, 3)

In [14]:
arr

array([[-0.64443668, -0.67115517, -0.30183937],
       [-0.72926768, -1.02674866,  0.33654977],
       [ 1.50518024, -1.8974333 , -0.49659352],
       [-1.9210754 ,  0.03072267,  0.63766189],
       [ 0.92475348,  0.55945573, -0.57837662],
       [ 1.051199  , -1.48808382,  0.18931218]])

np.dot() 等价与 @ 运算

In [15]:
np.dot(arr.T, arr)

array([[ 8.86341656, -2.78062162, -2.35922885],
       [-2.78062162,  7.63324325,  0.2135843 ],
       [-2.35922885,  0.2135843 ,  1.22794918]])

In [16]:
arr.T @ arr

array([[ 8.86341656, -2.78062162, -2.35922885],
       [-2.78062162,  7.63324325,  0.2135843 ],
       [-2.35922885,  0.2135843 ,  1.22794918]])

transpose 换轴

In [17]:
arr = np.arange(16).reshape((2, 2, 4))

In [18]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [19]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

对于更高维度的数组、transpose方法可以接受包含轴编号的元组、用于置换轴

swapaxes方法、接收一对轴编号作为参数，并对轴进行调整用于重组数据

* swapaxes方法返回的也是数据的视图、而没有对数据进行复制