In [1]:
import numpy as np

通用函数 ufunc， 是一种在ndarray数据中进行逐元素操作的函数。某些简单的函数接受一个或多个标量数值。
并产生一个或多个标量结果 —————— 数值 ？ 结果

* sqrt: 平方根
* exp: 标准差

In [17]:
arr = np.arange(10)

In [18]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [20]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [21]:
x = np.random.randn(8)

In [22]:
y = np.random.randn(8)

In [23]:
x

array([ 0.18467178, -0.22262806,  1.01248903,  1.34860825,  1.44286387,
       -1.0078163 ,  0.85968777,  0.34371786])

In [24]:
y

array([ 1.55172898, -1.75102284,  1.02321038, -0.08184053,  2.52486698,
        0.67889284, -0.3033256 , -0.12276576])

同时遍历两个数组、逐个元素比较，取出较大值

In [25]:
np.maximum(x, y)

array([ 1.55172898, -0.22262806,  1.02321038,  1.34860825,  2.52486698,
        0.67889284,  0.85968777,  0.34371786])

### 一元通用函数
* abs、fab：计算整数、浮点数或复数的绝对值   
* sqrt：平方根
* square：平方
* exp： 自然指数
* log、log10、log2、log1p： 自然对数、对数10为底、对数2、log（1+x）
* sign： 计算符号 正、 负、 0
* ceil： 最高整数
* floor： 最小整数
* rint： 保留整数位
* modf： 分别将数组的小数部分和整数部分按数组形式返回
* isnan： 返回数组中的元素是否为NaN， return bool
* isfinite、isinf： 分别返回数组中元素是否有限、是否无限 return bool
* cos、cosh、sin、sinh、tan、tanh： 三角函数
* arccos、arccosh、arcsin、arcsinh、arctan、arctanh： 反三角函数
* logical_not： 对数组的元素按位取反？

### 二元通用函数
* add： 加
* subtract： 减
* multiply： 乘
* divide、floor_divide： 除、整除
* power： n次方
* maximun、fmax： 最大值、fmax忽略NaN
* minimun、fmin： 最小值、fmin忽略NaN
* mod：求模计算  ？？？

In [26]:
x = np.array([1, 2, 3, 4])

In [27]:
y = np.array([2, 2, 2, 2])

In [28]:
np.power(x, y)

array([ 1,  4,  9, 16])

In [30]:
np.subtract(y, x)

array([ 1,  0, -1, -2])