In [3]:
import numpy as np

### 生成ndarray

1. array接受任意 [序列型对象], <br>生成一个新的包含传递数据NumP

In [4]:
data_1 = [6, 7.9, 8, 0, 1]

In [5]:
arr1 = np.array(data_1)

In [6]:
arr1

array([6. , 7.9, 8. , 0. , 1. ])

2. 嵌套序列，等长度的列表，将会转换 <b>多维数组</b>
    
<br>ndim 返回 数组行数 <br>
    shape 返回 数组尺寸

In [12]:
data_2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [13]:
arr2 = np.array(data_2)

In [14]:
arr2.ndim

2

In [15]:
arr2.shape

(2, 4)

3. 除非显示指定否则np.array会自动推断生成数组的数据类型, 数据类型被存储在一个特殊的元数据[dtype]中

In [18]:
arr1.dtype

dtype('float64')

In [19]:
arr2.dtype

dtype('int32')


* zeros: 创建全0数组
* ones: 创建全1数组
* empty: 创建一个没有初始化数值的数组
* full: 创建全指定参数的的数组
***

以上方法都有对应的like扩展方法
*_like: 根据所给数组的形状，生成一个相同形状的全[0、1、null、*]数组

In [29]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [31]:
np.empty((2, 3, 2))

array([[[9.39429932e-312, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [2.12199579e-314, 1.58817677e-052]],

       [[4.71751627e-090, 3.26696538e-032],
        [6.55039081e-043, 1.01335033e-070],
        [3.99910963e+252, 3.18299515e-313]]])

4. arange 是 Python内建函数range的数组版

In [32]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### ndarray的数据类型

In [33]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [34]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [37]:
arr1.dtype

dtype('float64')

In [38]:
arr2.dtype

dtype('int32')

dtype是NumPy能够与其他系统数据灵活交互的原因。通常，其他系统提供一个硬盘或<br>
内存与数据的对应关系，是的利用C或Fortran等底层语言读写数据变得十分方便。数<br>
数据的dtype通常是按照一个方式命名的

使用astype转换数组数据类型

* astype方法不是直接修改原数组的数据类型，而是返回一个新的 array对象

In [45]:
arr = np.array([1, 2, 3, 4, 5])

In [46]:
arr.dtype

dtype('int32')

In [47]:
float_arr = arr.astype(np.float64)

In [48]:
float_arr.dtype

dtype('float64')

In [51]:
arr = np.array([3.1, 4.32, 5.33])

In [53]:
float_arr = arr.astype(np.int32)

In [54]:
float_arr

array([3, 4, 5])

In [55]:
int_arr = float_arr.astype(np.float64)

In [56]:
int_arr

array([3., 4., 5.])

 浮点类型转成整数类型， 在转成浮点类型后会造成浮点后的数据丢书

In [58]:
numeric_string = np.array(['1.24', '2.4', '2.33'], dtype=np.string_)

In [62]:
numeric_string.astype(float)

array([1.24, 2.4 , 2.33])

* numpy使用字符串数据是，会修正其大小或删除输入且不发出警告
* 因为某些原因可能导致转换失败(比如 string_ 无法转换成 np.float64), <br>
  这里使用float代替np.float64。 因为NumPy可以使用相同别名来表征与Python精度相同的Python数据类型

可以使用其他array数组的dtype属性 进行类型转换

In [66]:
int_array = np.arange(10)

In [67]:
calibers = np.array([.22, .12, 1.44, 1.233, 6.4, .59], dtype=np.float64)

In [68]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

使用类型代码 'u4'

In [69]:
empty_uint32 = np.empty(8, dtype='u4')

In [70]:
empty_uint32

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=uint32)

### NumPy 算术

In [71]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [73]:
arr * arr

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [74]:
arr - arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [75]:
1 / arr

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.2       , 0.16666667, 0.14285714, 0.125     ]])

In [76]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712]])

* 同数组之间的比较会产生bool数组

In [82]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [83]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [84]:
arr2 > arr1

array([[False,  True, False],
       [ True, False,  True]])

不同尺寸的数据之间的操作将会用到广播特性

### 基础索引与切片

In [85]:
arr = np.arange(10)

In [86]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
arr[5]

5

In [88]:
arr[5:8]

array([5, 6, 7])

In [89]:
arr[5:8] = 12

In [90]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

 如果将一个值传递给数组的切片，会将这个值赋值给整个切片。
 * 区别与python的内建列表: 数组的切片是原数组的视图。这意味着数据并不是被复制了
  * 任何对于视图的修改都会反映到原数组上

In [91]:
l = range(10)

In [92]:
l

range(0, 10)

In [93]:
l[5:8]

range(5, 8)

python的内建列表并不支持对切片进行赋值这样的操作

In [95]:
l[5:8] = 12

TypeError: 'range' object does not support item assignment

* 可以使用copy()

In [97]:
sa = arr[5:8].copy()

多维度的数组可以更多的选择<br>

二维数组中， 每个索引值的是一个一维数组

In [98]:
arr2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [99]:
arr2d[1]

array([5, 6, 7, 8])

* 如果要定位到单个元素，可以使用类似嵌套列表的索引方式 array[n][m], 特别的 array[n, m] 与之等价

In [102]:
arr2d[0][2]

3

In [103]:
arr2d[0, 2]

3

* 可以展示二维数组上的索引， 0轴看做行， 1轴看做列

In [104]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [105]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [106]:
arr3d.shape

(2, 2, 3)

In [107]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [108]:
arr3d[0].shape

(2, 3)

* 标量和数组都可以传递给arr3d[0]

In [114]:
old_values = arr3d[0].copy()

In [115]:
arr3d[0] = 42

In [116]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [117]:
arr3d[0] = old_values

In [118]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [119]:
arr3d[1, 0]

array([7, 8, 9])

In [120]:
x = arr3d[1]

In [121]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [122]:
x[0]

array([7, 8, 9])

In [123]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [124]:
arr[1:6]

array([ 1,  2,  3,  4, 12])

In [125]:
arr2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [126]:
arr2d[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [127]:
arr2d[:2, 1:]

array([[2, 3, 4],
       [6, 7, 8]])